name: Update Logstash Configuration on Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - 'logstash.conf'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PC2UBUNTU }}

    - name: Sync logstash.conf
      run: scp -o StrictHostKeyChecking=no ./logstash.conf ubuntu@52.195.12.82:/home/ubuntu/elk/config/logstash.conf

    - name: Update logstash-cm.yaml
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.195.12.82 "\
        sed -i '/input/,\$d' /home/ubuntu/elk/config/logstash-cm.yaml && \
        cat /home/ubuntu/elk/config/logstash.conf >> /home/ubuntu/elk/config/logstash-cm.yaml && \
        sed -i '/input/,\$ s/^/    /' /home/ubuntu/elk/config/logstash-cm.yaml"

    - name: Apply the new ConfigMap
      run: ssh -o StrictHostKeyChecking=no ubuntu@52.195.12.82 "kubectl apply -f /home/ubuntu/elk/config/logstash-cm.yaml"

    - name: Apply the new Deployment
      run: ssh -o StrictHostKeyChecking=no ubuntu@52.195.12.82 "kubectl rollout restart /home/ubuntu/elk/config/logstash-deployment.yaml"


