name: SSH Connection Test

on:
  push:
    branches:
      - main  # 或者你用于测试的分支
   
jobs:
  ssh-connection-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PC2UBUNTU }}

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no ubuntu@52.195.12.82 "echo 'SSH connection successful!'"
