name: SSH Connection Test

on:
  push:
    branches:
      - main  # 或者你用于测试的分支
    paths-ignore:
      - '**'  # 忽略所有路径，除非明确推送，可以修改为具体文件以限定测试触发条件

jobs:
  ssh-connection-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PC2UBUNTU }}

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no user@52.195.12.82 "echo 'SSH connection successful!'"
